development/tora: also allow building against bindings installed oracle-xe-11g

diff --git a/development/tora/tora.SlackBuild b/development/tora/tora.SlackBuild
--- a/development/tora/tora.SlackBuild
+++ b/development/tora/tora.SlackBuild
@@ -25,7 +25,7 @@
 PRGNAM=tora
 VERSION=${VERSION:-2.1.3}
 ORACLEVERS=${ORACLEVERS:-11.2}
-BUILD=${BUILD:-4}
+BUILD=${BUILD:-5}
 TAG=${TAG:-_acl}
 
 if [ -z "$ARCH" ]; then
@@ -75,7 +75,24 @@ find -L . \
 
 ORACLE_FLAGS=""
 if [ "${WITH_ORACLE}" = "yes" ]; then
-  ORACLE_FLAGS="-DORACLE_PATH_INCLUDES="/usr/include/oracle/$ORACLEVERS/client$LIBDIRSUFFIX" -DORACLE_PATH_LIB="$ORACLE_HOME/lib""
+  if [ "x$ORACLE_HOME" = "x" ] ; then
+    echo "ORACLE_HOME is not set"
+    exit 1
+  fi
+
+  ORACLE_INCLUDE=${ORACLE_INCLUDE:-}
+
+  if [ "x$ORACLE_INCLUDE" = "x" ] ; then
+    if [ -e "/usr/include/oracle/$ORACLEVERS/client$LIBDIRSUFFIX" ] ; then
+      ORACLE_INCLUDE=/usr/include/oracle/$ORACLEVERS/client$LIBDIRSUFFIX
+    elif [ -e /u01/app/oracle/product/11.2.0/xe/rdbms/public ] ; then
+      ORACLE_INCLUDE=/u01/app/oracle/product/11.2.0/xe/rdbms/public
+    else
+      echo "Oracle includes not found"
+      exit 1
+    fi
+  fi
+  ORACLE_FLAGS="-DORACLE_PATH_INCLUDES="$ORACLE_FLAGS" -DORACLE_PATH_LIB="$ORACLE_HOME/lib""
 fi
 
 mkdir -p build
@@ -88,7 +105,7 @@ cd build
     -DLIB_SUFFIX=${LIBDIRSUFFIX} \
     -DMAN_INSTALL_DIR=/usr/man \
     -DCMAKE_BUILD_TYPE=Release ..
-  make 
+  make
   make install DESTDIR=$PKG
 
 cd ..
